name: Tests
on: 
  pull_request:
  push:
      branches:
        - master
jobs:
  Tests:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{vars.ANDROID_SDK_ROOT}}
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Start Genymotion Cloud SaaS instance
        uses: genymobile/genymotion-saas-github-action@v1
        with:
          api_token: ${{ secrets.GMSAAS_API_TOKEN }}
          recipe_uuid: ${{ vars.GMSAAS_RECIPE_UUID }}
      - name: Run tests
        run: bash scripts/run_tests.bash
      - name: Run screenshot tests
        run: |
          bash scripts/run_screenshots.sh
          zip -r screenshots.zip screenshots
      - name: Publish Unit Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: "app/build/test-results/testDebugUnitTest/*.xml"
          check_name: UnitTests
      - name: Publish Instrumentation Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: "app/build/outputs/androidTest-results/connected/**/*.xml"
          check_name: InstrumentationTests
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive unit tests
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests
          path: app/build/reports/tests/testDebugUnitTest
      - name: Archive instrumentation tests
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-tests
          path: app/build/reports/androidTests/connected/debug
      - name: Archive coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: app/build/reports/jacoco
      - name: Archive logcat
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logcat
          path: /tmp/lolcat.log
      - name: Archive apks
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            ./app/build/outputs/apk/debug/app-debug.apk
            ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
      - name: Archive screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            ./screenshots.zip
